# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: ABOUT
    url: about
    weight: 10

  - name: CONNECT
    url: connect
    weight: 20
  - name: LEARN & TEACH
    weight: 30
  - name: Digital Training & Champions Initiative
    parent: LEARN & TEACH
    url: learn-teach/tracks
    weight: 10
  - name: Workshops & Courses
    parent: LEARN & TEACH
    url: learn-teach/workshops
    weight: 10
  



  - name: FIND & SHARE
    url: find-share
    weight: 40

  - name: EVENTS
    url: event
    weight: 50
  - name: PEOPLE
    url: people
    weight: 60
  - name: BLOG
    url: post
    weight: 70
  - name: CONTACT
    url: contact
    weight: 80
